// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.5
// source: gocrypto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest_OrderType int32

const (
	CreateOrderRequest_Market CreateOrderRequest_OrderType = 0
	CreateOrderRequest_Limit  CreateOrderRequest_OrderType = 1
)

// Enum value maps for CreateOrderRequest_OrderType.
var (
	CreateOrderRequest_OrderType_name = map[int32]string{
		0: "Market",
		1: "Limit",
	}
	CreateOrderRequest_OrderType_value = map[string]int32{
		"Market": 0,
		"Limit":  1,
	}
)

func (x CreateOrderRequest_OrderType) Enum() *CreateOrderRequest_OrderType {
	p := new(CreateOrderRequest_OrderType)
	*p = x
	return p
}

func (x CreateOrderRequest_OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateOrderRequest_OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_gocrypto_proto_enumTypes[0].Descriptor()
}

func (CreateOrderRequest_OrderType) Type() protoreflect.EnumType {
	return &file_gocrypto_proto_enumTypes[0]
}

func (x CreateOrderRequest_OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateOrderRequest_OrderType.Descriptor instead.
func (CreateOrderRequest_OrderType) EnumDescriptor() ([]byte, []int) {
	return file_gocrypto_proto_rawDescGZIP(), []int{3, 0}
}

type CreateOrderRequest_OrderSide int32

const (
	CreateOrderRequest_Buy  CreateOrderRequest_OrderSide = 0
	CreateOrderRequest_Sell CreateOrderRequest_OrderSide = 1
)

// Enum value maps for CreateOrderRequest_OrderSide.
var (
	CreateOrderRequest_OrderSide_name = map[int32]string{
		0: "Buy",
		1: "Sell",
	}
	CreateOrderRequest_OrderSide_value = map[string]int32{
		"Buy":  0,
		"Sell": 1,
	}
)

func (x CreateOrderRequest_OrderSide) Enum() *CreateOrderRequest_OrderSide {
	p := new(CreateOrderRequest_OrderSide)
	*p = x
	return p
}

func (x CreateOrderRequest_OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateOrderRequest_OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_gocrypto_proto_enumTypes[1].Descriptor()
}

func (CreateOrderRequest_OrderSide) Type() protoreflect.EnumType {
	return &file_gocrypto_proto_enumTypes[1]
}

func (x CreateOrderRequest_OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateOrderRequest_OrderSide.Descriptor instead.
func (CreateOrderRequest_OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_gocrypto_proto_rawDescGZIP(), []int{3, 1}
}

type OpenMatchingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OpenPrice float32 `protobuf:"fixed32,2,opt,name=openPrice,proto3" json:"openPrice,omitempty"`
}

func (x *OpenMatchingRequest) Reset() {
	*x = OpenMatchingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gocrypto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenMatchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenMatchingRequest) ProtoMessage() {}

func (x *OpenMatchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gocrypto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenMatchingRequest.ProtoReflect.Descriptor instead.
func (*OpenMatchingRequest) Descriptor() ([]byte, []int) {
	return file_gocrypto_proto_rawDescGZIP(), []int{0}
}

func (x *OpenMatchingRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OpenMatchingRequest) GetOpenPrice() float32 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

type CloseMatchingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *CloseMatchingRequest) Reset() {
	*x = CloseMatchingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gocrypto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseMatchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseMatchingRequest) ProtoMessage() {}

func (x *CloseMatchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gocrypto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseMatchingRequest.ProtoReflect.Descriptor instead.
func (*CloseMatchingRequest) Descriptor() ([]byte, []int) {
	return file_gocrypto_proto_rawDescGZIP(), []int{1}
}

func (x *CloseMatchingRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gocrypto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_gocrypto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_gocrypto_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    string                       `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Qty       float32                      `protobuf:"fixed32,2,opt,name=qty,proto3" json:"qty,omitempty"`
	Price     float32                      `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	OrderType CreateOrderRequest_OrderType `protobuf:"varint,4,opt,name=orderType,proto3,enum=gocrypto.CreateOrderRequest_OrderType" json:"orderType,omitempty"`
	OrderSide CreateOrderRequest_OrderSide `protobuf:"varint,5,opt,name=orderSide,proto3,enum=gocrypto.CreateOrderRequest_OrderSide" json:"orderSide,omitempty"`
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gocrypto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gocrypto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_gocrypto_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateOrderRequest) GetQty() float32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CreateOrderRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderRequest) GetOrderType() CreateOrderRequest_OrderType {
	if x != nil {
		return x.OrderType
	}
	return CreateOrderRequest_Market
}

func (x *CreateOrderRequest) GetOrderSide() CreateOrderRequest_OrderSide {
	if x != nil {
		return x.OrderSide
	}
	return CreateOrderRequest_Buy
}

type ModifyOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string  `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Qty     float32 `protobuf:"fixed32,2,opt,name=qty,proto3" json:"qty,omitempty"`
	Price   float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *ModifyOrderRequest) Reset() {
	*x = ModifyOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gocrypto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyOrderRequest) ProtoMessage() {}

func (x *ModifyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gocrypto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyOrderRequest.ProtoReflect.Descriptor instead.
func (*ModifyOrderRequest) Descriptor() ([]byte, []int) {
	return file_gocrypto_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ModifyOrderRequest) GetQty() float32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *ModifyOrderRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol  string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId string `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gocrypto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gocrypto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_gocrypto_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OrderLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *OrderLogResponse) Reset() {
	*x = OrderLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gocrypto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLogResponse) ProtoMessage() {}

func (x *OrderLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gocrypto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLogResponse.ProtoReflect.Descriptor instead.
func (*OrderLogResponse) Descriptor() ([]byte, []int) {
	return file_gocrypto_proto_rawDescGZIP(), []int{6}
}

func (x *OrderLogResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_gocrypto_proto protoreflect.FileDescriptor

var file_gocrypto_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x6f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x6f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x13, 0x4f, 0x70,
	0x65, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65,
	0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6f, 0x70,
	0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0xa4, 0x02, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x71,
	0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x67, 0x6f,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x44,
	0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x26, 0x2e, 0x67, 0x6f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x69, 0x64, 0x65, 0x22, 0x22, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x10, 0x01, 0x22, 0x1e, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x69, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x75, 0x79, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x53, 0x65, 0x6c, 0x6c, 0x10, 0x01, 0x22, 0x56, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x46, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x32, 0xf7, 0x02, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x4f, 0x70, 0x65, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x4f,
	0x70, 0x65, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x6f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x6f, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x49, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c,
	0x2e, 0x67, 0x6f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67,
	0x6f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0b, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x70, 0x33, 0x69, 0x73, 0x6d, 0x70, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gocrypto_proto_rawDescOnce sync.Once
	file_gocrypto_proto_rawDescData = file_gocrypto_proto_rawDesc
)

func file_gocrypto_proto_rawDescGZIP() []byte {
	file_gocrypto_proto_rawDescOnce.Do(func() {
		file_gocrypto_proto_rawDescData = protoimpl.X.CompressGZIP(file_gocrypto_proto_rawDescData)
	})
	return file_gocrypto_proto_rawDescData
}

var file_gocrypto_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gocrypto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gocrypto_proto_goTypes = []interface{}{
	(CreateOrderRequest_OrderType)(0), // 0: gocrypto.CreateOrderRequest.OrderType
	(CreateOrderRequest_OrderSide)(0), // 1: gocrypto.CreateOrderRequest.OrderSide
	(*OpenMatchingRequest)(nil),       // 2: gocrypto.OpenMatchingRequest
	(*CloseMatchingRequest)(nil),      // 3: gocrypto.CloseMatchingRequest
	(*Response)(nil),                  // 4: gocrypto.Response
	(*CreateOrderRequest)(nil),        // 5: gocrypto.CreateOrderRequest
	(*ModifyOrderRequest)(nil),        // 6: gocrypto.ModifyOrderRequest
	(*CancelOrderRequest)(nil),        // 7: gocrypto.CancelOrderRequest
	(*OrderLogResponse)(nil),          // 8: gocrypto.OrderLogResponse
}
var file_gocrypto_proto_depIdxs = []int32{
	0, // 0: gocrypto.CreateOrderRequest.orderType:type_name -> gocrypto.CreateOrderRequest.OrderType
	1, // 1: gocrypto.CreateOrderRequest.orderSide:type_name -> gocrypto.CreateOrderRequest.OrderSide
	2, // 2: gocrypto.Exchange.OpenMatching:input_type -> gocrypto.OpenMatchingRequest
	3, // 3: gocrypto.Exchange.CloseMatching:input_type -> gocrypto.CloseMatchingRequest
	5, // 4: gocrypto.Exchange.CreateOrder:input_type -> gocrypto.CreateOrderRequest
	7, // 5: gocrypto.Exchange.CancelOrder:input_type -> gocrypto.CancelOrderRequest
	6, // 6: gocrypto.Exchange.ModifyOrder:input_type -> gocrypto.ModifyOrderRequest
	4, // 7: gocrypto.Exchange.OpenMatching:output_type -> gocrypto.Response
	4, // 8: gocrypto.Exchange.CloseMatching:output_type -> gocrypto.Response
	8, // 9: gocrypto.Exchange.CreateOrder:output_type -> gocrypto.OrderLogResponse
	8, // 10: gocrypto.Exchange.CancelOrder:output_type -> gocrypto.OrderLogResponse
	8, // 11: gocrypto.Exchange.ModifyOrder:output_type -> gocrypto.OrderLogResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gocrypto_proto_init() }
func file_gocrypto_proto_init() {
	if File_gocrypto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gocrypto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenMatchingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gocrypto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseMatchingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gocrypto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gocrypto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gocrypto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gocrypto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gocrypto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gocrypto_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gocrypto_proto_goTypes,
		DependencyIndexes: file_gocrypto_proto_depIdxs,
		EnumInfos:         file_gocrypto_proto_enumTypes,
		MessageInfos:      file_gocrypto_proto_msgTypes,
	}.Build()
	File_gocrypto_proto = out.File
	file_gocrypto_proto_rawDesc = nil
	file_gocrypto_proto_goTypes = nil
	file_gocrypto_proto_depIdxs = nil
}
